### PR TITLE
Selfie: Make QrImageAnalyzer use BottomSheetDialog

### PR DESCRIPTION
**Pull request by luk1337**
Change-Id: Ic489dda6c762b29ba13d35d63433334bb88119d2

### CODE REVIEW

**Comment by luk1337** [comment]
Is this any better?
image

**Comment by luk1337** [comment]
Maybe would be good to also make it display barcode type and allow switching between text and bytes, but not sure how to make that nice UI wise

**Comment by luk1337** [comment]
Very basic but still looks better I think?
image

**Comment by luca020400** [comment]
I'd move the share/copy next to the text
Right now the UX isn't really clear on what these buttons actually copy/share

**Comment by luk1337** [comment]
ADB Screenshot from 2022-08-14 12-09-30
ADB Screenshot from 2022-08-14 12-09-26

**Comment by luk1337** [comment]
> I'd move the share/copy next to the text Right now the UX isn't really clear on what these buttons actually copy/share

eh, I don't really think that's ok...

**Comment by luk1337** [comment]
Added copy toast msgs ^.^

**Comment by luca020400** [comment]
> Added copy toast msgs ^.^

Well that's bothering on 13, as there's a UI element that pops up whenever you copy something
Is the toast really needed? If the button has a ripple animation is easy to see

**Comment by luk1337** [comment]
> > Added copy toast msgs ^.^
> 
> Well that's bothering on 13, as there's a UI element that pops up whenever you copy something Is the toast really needed? If the button has a ripple animation is easy to see

I think it's nice that way?

**Review by luca020400 — APPROVED** [review]

**Pull request merged**
