### PR TITLE
Selfie: Hide torch/flash mode if there's no flash unit

### PR DESCRIPTION
**Pull request by luk1337**
Change-Id: Ibb7271f1737e7530590b43864853138f2eb13718

### CODE REVIEW

**Comment by luca020400** [comment]
I guess this just make the section empty?
Anyways, we should do the same for available extensions

**Comment by luk1337** [comment]
It seems to behave and look properly?

**Comment by luk1337** [comment]
ADB Screenshot from 2022-08-09 14-47-54

**Comment by luca020400** [comment]
Oh lol
I didn't expect that, but coordinator layout is magic

**Review by luca020400 — APPROVED** [review]

**Pull request merged**
