### PR TITLE
Re-bind onResume

### PR DESCRIPTION
**Pull request by luca020400**
Signed-off-by: Luca Stefani <luca.stefani.ge1@gmail.com>
Change-Id: If7ce54eafe8d8415e9fd659b027353e16780cb4c

### CODE REVIEW

**Comment by luca020400** [comment]
We need to move some bits to onResume

**Comment by SebaUbuntu** [comment]
Photo capture mode now gets applied instantly, this can be merged as is or there's some other things to do?

**Comment by luca020400** [comment]
This works fine, but now on startup we bind twice, that's wrong, we should instead start to split initialization between create and resume
Blocking for now

**Comment by SebaUbuntu** [comment]
> This works fine, but now on startup we bind twice, that's wrong, we should instead start to split initialization between create and resume Blocking for now

I tried to remove the call to bindCameraUseCases from onCreate and just call that from onResume, everything still works, should I push that?

**Comment by luca020400** [comment]
If it works good
Now we bind before setting some entries, if that's correct go for it

**Pull request merged**
