### PR TITLE
Selfie: Use glide for loading last thumbnail

### PR DESCRIPTION
**Pull request by luk1337**
Change-Id: If28ecdd84cfa0f6954ea941caf018378fff60eb8

### CODE REVIEW

**Comment by luk1337** [comment]
Mostly uploading that here to get some kind of alternative solution to this problem. Loading thumbnails with Glide fixes FFC thumbnail rotation here.

**Comment by luk1337** [comment]
Also, some gallery apps are able to handle this issue while others can't. For example, aosp gallery3d doesn't rotate the photo, but google photos does.

**Review by SebaUbuntu — APPROVED** [review]
I saw also CameraXBasic app example uses it

**Comment by luk1337** [comment]
Coin seems nicer.

**Pull request closed without merging**
