### PR TITLE
Selfie: Import new shutter AVDs

### PR DESCRIPTION
**Pull request by luk1337**
Change-Id: I8fa1064583eb12c3c50906bb58da1475adfd6532

### CODE REVIEW

**Comment by luk1337** [comment]
Fixed video start/end animations:
https://user-images.githubusercontent.com/6830979/186892554-c2770ff6-2644-45e3-83f5-f96afb381358.mp4

**Comment by luca020400** [comment]
That's sick!

**Review by SebaUbuntu — APPROVED** [review]
Everything is fine here, awesome as well, merge when ready

**Review by luca020400 — APPROVED** [review]
Works

**Pull request merged**
