### PR TITLE
Selfie: Override camera2

### PR DESCRIPTION
**Pull request by althafvly**
Change-Id: I6bba7f8ab5eaf2b15250f8a9de69c0cd717893ae

### CODE REVIEW

**Comment by luk1337** [comment]
Not sure if it won't be the other way around, aka Selfie for everyone, Camera2 for those that want it.

**Comment by althafvly** [comment]
> Not sure if it won't be the other way around, aka Selfie for everyone, Camera2 for those that want it.

So there will be two apps?

**Comment by luk1337** [comment]
Well, if there's some legacy junk that doesn't work with camerax, I guess?

**Comment by althafvly** [comment]
> Well, if there's some legacy junk that doesn't work with camerax, I guess?

sad, keeping this here. incase if we wanna kill camera2

**Comment by luk1337** [comment]
> > Well, if there's some legacy junk that doesn't work with camerax, I guess?
> 
> sad, keeping this here. incase if we wanna kill camera2

I think in this case, we could just not sync Camera2...

**Comment by althafvly** [comment]
> > > Well, if there's some legacy junk that doesn't work with camerax, I guess?
> > 
> > 
> > sad, keeping this here. incase if we wanna kill camera2
> 
> I think in this case, we could just not sync Camera2...

:(

**Comment by luk1337** [comment]
I think the go-to is to make Camera2 override Selfie and remove Camera2 (or replace with Selfie) in build/make/target/product/handheld_product.mk.

**Pull request closed without merging**
